BACKUP DATABASE DBNAME TO DISK='PATH '
WITH DIFFERENTIAL
BACKUP LOG DBNAME TO DISK=''

RESTORE DATABASE DBNAME FROM DISK='' 
WITH MOVE 'LOGICALFNAME' TO 'PHYSICAPATH'
,MOVE 'LOGICALNAME' TO 'PHYSPATH',
NORECOVERY